In [1]:
import numpy as np

In [10]:
a = np.array([1,3,2])#1d array using numpy
print(a)
print(type(a))

[1 3 2]
<class 'numpy.ndarray'>


In [8]:
a = np.array(([1,2,2],[3,2,5]))#2d array using numpy
print(a)

[[1 2 2]
 [3 2 5]]


In [15]:
a = np.array(([[1,2,3],[2,3,4]],[[1,3,5],[6,7,8]]))#3d array using numpy
print(a)
print("array size is",a.ndim)

[[[1 2 3]
  [2 3 4]]

 [[1 3 5]
  [6 7 8]]]
array size is 3


In [17]:
a = np.array([1,3,2])
print("1st element is",a[0])
print("2nd element is",a[1])
print("3rd element is",a[2])

1st element is 1
2nd element is 3
3rd element is 2


In [19]:
a = np.array([1,3,2])
print("last element is",a[-1])
print("2nd last element is",a[-2])
print("3rd last element is",a[-3])

last element is 2
2nd last element is 3
3rd last element is 1


In [22]:
a = np.array(([1,2,2],[3,2,5]))
print("Row1:",a[0])
print("Row2:",a[1])
print("Row 2, col 1 =",[2,1])


Row1: [1 2 2]
Row2: [3 2 5]
Row 2, col 1 = [2, 1]


In [25]:
a = np.array(([1,2,3,4],[5,6,7,8],[12,14,16,18],[21,23,25,27]))
print(a)
print(a[-2,-4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [12 14 16 18]
 [21 23 25 27]]
12


In [34]:
a = np.array(([33,11,99,22,66,44,88]))
print(a[0:3])
print(a[-3:])
print(a[3:])

[33 11 99]
[66 44 88]
[22 66 44 88]


In [36]:
print(a[::1])
print(a[1::2])
print(a[0:6:3])

[33 11 99 22 66 44 88]
[11 22 44]
[33 22]


In [37]:
print(a[-1::-1])
print(a[1::2])
print(a[0:6:3])

[88 44 66 22 99 11 33]
[11 22 44]
[33 22]
