In [1]:
import numpy as np

arr1 = np.array([1,3,5,6])
arr2 = np.array(([1,2,3],[2,4,6]))
print("type arr1 = ",type(arr1))
print("arr2 = \n",arr2)

type arr1 =  <class 'numpy.ndarray'>
arr2 = 
 [[1 2 3]
 [2 4 6]]


In [5]:
a = np.linspace(start = 0,stop = 10,num=20,endpoint = True)
print(a)
print()
a = np.linspace(start = 0,stop = 10,num=20,endpoint = True,retstep = True)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]), 0.5263157894736842)


In [7]:
a = np.arange(start = 0, stop = 5,step = 0.2)
print(a)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


In [9]:
a=np.ones((2,3))
print(a,"\n")
a = np.zeros((4,5))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
a = np.random.rand(3)
print(a,"\n")
np.random.rand(3,4)

[0.64967611 0.8267322  0.30752629] 



array([[0.94353373, 0.5785148 , 0.19134134, 0.48673803],
       [0.98212274, 0.20073505, 0.86185067, 0.64185241],
       [0.5246242 , 0.39937585, 0.13613356, 0.67342905]])

In [20]:
np.random.randint(low =4,high = 16,size =8)

array([14,  4, 11, 13,  6, 10, 15, 10])

In [25]:
np.logspace(1,10,num=5,endpoint = True, base = 2 )

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [32]:
print(arr2,"\n")
print(arr2.reshape(3,2))


[[1 2 3]
 [2 4 6]] 

[[1 2]
 [3 2]
 [4 6]]


In [33]:
arr2.shape


(2, 3)

In [38]:
arr = np.array(([12,23,45,67,3],[33,2,5,77,1]))

print("SUM = ",np.sum(arr))
print("Axis 0 = ",np.sum(arr,axis = 0))
print("Axis 1 = ",np.sum(arr,axis = 1))

SUM =  268
Axis 0 =  [ 45  25  50 144   4]
Axis 1 =  [150 118]


In [46]:
a = np.arange(start = 2, stop = 8,step = 1)
b = np.random.randint(low =5,high = 20, size = a.shape[0])
print(a)
print(b)
np.add(a,b)

[2 3 4 5 6 7]
[18  5 13 10 17  7]


array([20,  8, 17, 15, 23, 14])

In [47]:
np.multiply(a,b)

array([ 36,  15,  52,  50, 102,  49])

In [48]:
print(arr)
np.transpose(arr)

[[12 23 45 67  3]
 [33  2  5 77  1]]


array([[12, 33],
       [23,  2],
       [45,  5],
       [67, 77],
       [ 3,  1]])

In [55]:
a = np.append(arr,[[23,42,3,4,66]],axis =0)
a

array([[12, 23, 45, 67,  3],
       [33,  2,  5, 77,  1],
       [23, 42,  3,  4, 66]])

In [57]:
i = np.insert(a,0,[2,3,4,1,6],axis = 0)
i

array([[ 2,  3,  4,  1,  6],
       [12, 23, 45, 67,  3],
       [33,  2,  5, 77,  1],
       [23, 42,  3,  4, 66]])

In [59]:
i= np.delete(i, 3, axis =0)
i

array([[ 2,  3,  4,  1,  6],
       [12, 23, 45, 67,  3],
       [33,  2,  5, 77,  1]])

In [68]:
a = np.matrix("2,4,5;22,45,7")
print(a)

[[ 2  4  5]
 [22 45  7]]


In [69]:
a.shape

(2, 3)

In [70]:
a.shape[1]

3

In [71]:
a.size

6

In [73]:
col = np.matrix("1,3,5")
a = np.insert(a,1,col,axis = 0)
a

matrix([[ 2,  4,  5],
        [ 1,  3,  5],
        [22, 45,  7]])

In [75]:
a = np.matrix(np.arange(0,20)).reshape(4,5)
b = np.matrix(np.arange(10,30)).reshape(4,5)
c = np.add(a,b)
c

matrix([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48]])

In [76]:
c = np.subtract(a,b)
c

matrix([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]])

In [78]:
c = np.multiply(a,b)
c

matrix([[  0,  11,  24,  39,  56],
        [ 75,  96, 119, 144, 171],
        [200, 231, 264, 299, 336],
        [375, 416, 459, 504, 551]])

In [80]:
c = np.dot(a,b.transpose())
c

matrix([[ 130,  180,  230,  280],
        [ 430,  605,  780,  955],
        [ 730, 1030, 1330, 1630],
        [1030, 1455, 1880, 2305]])

In [81]:
c= np.divide(a,b)
c

matrix([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
        [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421],
        [0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333],
        [0.6       , 0.61538462, 0.62962963, 0.64285714, 0.65517241]])

In [84]:
a = np.array(([1,4,7],[2,6,4],[9,7,6]))
det = np.linalg.det(a)
det

-176.00000000000009

In [87]:
rank = np.linalg.matrix_rank(a)
rank

3

In [88]:
inv = np.linalg.inv(a)
inv

array([[-0.04545455, -0.14204545,  0.14772727],
       [-0.13636364,  0.32386364, -0.05681818],
       [ 0.22727273, -0.16477273,  0.01136364]])

In [90]:
e = np.matrix("1,2,6;2,4,6;3,4,5")
f = np.matrix("3,4,5").transpose()

sol = np.linalg.solve(e,f)
sol


matrix([[ 1.33333333],
        [-0.16666667],
        [ 0.33333333]])